sudo: required
services:
  - docker

before_install:
  - docker build -t 1macdocker1/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true 1macdocker1/react-test npm test

after_success:
  - docker build -t 1macdocker1/multi-client ./client
  - docker build -t 1macdocker1/multi-nginx ./nginx
  - docker build -t 1macdocker1/multi-server ./server
  - docker build -t 1macdocker1/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push 1macdocker1/multi-client
  - docker push 1macdocker1/multi-nginx
  - docker push 1macdocker1/multi-server
  - docker push 1macdocker1/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-988001772269"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY